### ISSUE TITLE
why are there header files in project that claims to use C++ 20?

### ISSUE THREAD

**Issue by rds1983** [LucidSigma/stardust#1]
Doesnt C++20 have modules?

**Comment by LucidSigma** [comment]
Most C++ compilers do not fully support modules at the time I wrote this (including MSVC: the one I used); hence why I didn't use them.

The project makes use of some minor C++20 features (ranged-based for loop variable initialisation, std::unordered_set::contains(), [[likely]] attributes, et cetera), which is why I said the project uses C++20.

**Comment by rds1983** [comment]
I see. Thanks for the clarification.
